### PR TITLE
chore(bower): adding bower.json to fix bower installs

### PR DESCRIPTION
**Pull request by NathanWalker**
bower install is currently installing the old version 0.5.5. Adding a bower.json to help target specific versions to avoid the bower headache that I just went through.

Thanks for a great solution and library!

### CODE REVIEW

**Comment by jpillora** [comment]
Hi Nathan, thanks for the PR, sorry I'm a bower noob :blush:

**Comment by NathanWalker** [comment]
N/p at all.
Bower really depends on the tags on the repo and what tag is specified as the latest in bower.json.

So in the future, after building out new `dist` and pushing, just remember to tag it up and bump the bower.json file to match the tag and all the bower users will be happy :+1: 

Again, thanks for great solution. Just love this!

**Comment by NathanWalker** [comment]
Oh wait!!

Actually we are not set yet, you still need to create the new tag. I created a 0.5.6 tag on my fork however the PR will not satisfy the tag on your repo, so please create a 0.5.6 tag (I use `git flow`):

```
git flow release start 0.5.6
git flow release finish 0.5.6
git push 
git push --tags
```

**Comment by jpillora** [comment]
Tagged https://github.com/jpillora/xdomain/releases/tag/0.5.6 Ah yes, I was looking into bower for internal dependencies (XHook) and did a `bower register xdomain` and tagged 0.5.5, though I've forgotten since. Will remember from now :)

**Comment by jpillora** [comment]
I use http://www.sourcetreeapp.com/, much faster than CLI, it has git flow built in too

**Pull request merged**
